### Numpy Arrays and it's basic operations

##### Note : Dimensions in numpy means axes

In [2]:
# import required libraries

import numpy as np
import matplotlib.pyplot as plt
from numpy import random

In [3]:
# create numpy array using list
list_1 = [1, 2, 3, 4, 5]
np_array_1 = np.array(list_1, dtype = np.int8)

np_array_1

array([1, 2, 3, 4, 5], dtype=int8)

In [7]:
m_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
m_array = np.array(m_list)

# axes in the array
print(f"Multi-Dimensional Array : {m_array.ndim}")

# shape of the array
print(f"Shape of the array : {m_array.shape}")

# size of the array
print(f"Size of the array : {m_array.size}")

Multi-Dimensional Array : 2
Shape of the array : (3, 3)
Size of the array : 9


In [14]:
# creating array using tuple
tup = (1, 2, 3, 4)
tup_array = np.array(tup, dtype = np.int16)

print(tup_array.dtype)
print(f"Shape of the array : {tup_array.shape}")
print(f"Dimensions of the array : {tup_array.ndim}")

print()

mtup = ((1, 2, 3, 4), (5, 6, 7, 8))
mtup_array = np.array(mtup)
print(f"Dimensions of the array : {mtup_array.ndim}")
print(f"Shape of the array : {mtup_array.shape}")

int16
Shape of the array : (4,)
Dimensions of the array : 1

Dimensions of the array : 2
Shape of the array : (2, 4)


In [19]:
# arange -> it used to returns the evenly specified values with the interval (step size)
# Note : Step size is optional
# dummy_array = np.arange(0, 10, 2)
dummy_array = np.arange(0, 10)

print(f"Evenly specified array : {dummy_array}")

Evenly specified array : [0 1 2 3 4 5 6 7 8 9]


In [29]:
# linspace -> returns the evenly specified values within the interval
# Note : if the last paramater is not given then it returns the array of 50 items
interval_array = np.linspace(0, 5, 7)

print(f"Linspace array : {interval_array}")

Linspace array : [0.         0.83333333 1.66666667 2.5        3.33333333 4.16666667
 5.        ]


In [42]:
# creating array and fill with default values
# Note : it used to create an Scaler, vector and multi-dimensional array
# Dtype also specified while defining the zeros array

# Scalar array
scalar = np.zeros(8)

print(f"Scalar array : {scalar}")

print()

# Vector array
zero_array = np.zeros((2, 3))

print(f"Zero array :\n {zero_array}")
print(f"Dimension of the array : {zero_array.ndim}")
print(f"Shape of the array : {zero_array.shape}")

print()

# Multi-Dimensional array
multiArray = np.zeros((4, 3, 2))

print(f"Multi-Dimensional Array :\n {multiArray}")
print(f"Dimension of the array : {multiArray.ndim}")
print(f"Shape of the array : {multiArray.shape}")

# Data type of the array
print(f"Data type of the array : {multiArray.dtype}")

Scalar array : [0. 0. 0. 0. 0. 0. 0. 0.]

Zero array :
 [[0. 0. 0.]
 [0. 0. 0.]]
Dimension of the array : 2
Shape of the array : (2, 3)

Multi-Dimensional Array :
 [[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
Dimension of the array : 3
Shape of the array : (4, 3, 2)
Data type of the array : float64


In [48]:
# creating an empty array filled with value 1
# it is also used to craete an scalar, vector and multi-dimensional array

# scalar array
scalar_array = np.ones(10)

print(f"Scalar Array : {scalar_array}\n")

# vector array
vector_array = np.ones((2, 3))

print(f"\nMulti-Dimensional Array :\n {vector_array}")
print(f"Dimension of the array : {vector_array.ndim}")
print(f"Shape of the array : {vector_array.shape}")

# multi-dimensional array
multi_array = np.ones((4, 2, 3)) # [vector, vectorsize, vectorcolumn] -> (4, 2, 3)

print(f"\n\nMulti-Dimensional Array :\n {multi_array}")
print(f"Dimension of the array : {multi_array.ndim}")
print(f"Shape of the array : {multi_array.shape}")

Scalar Array : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Multi-Dimensional Array :
 [[1. 1. 1.]
 [1. 1. 1.]]
Dimension of the array : 2
Shape of the array : (2, 3)


Multi-Dimensional Array :
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
Dimension of the array : 3
Shape of the array : (4, 2, 3)
